[theme]
# Base theme config
base = "light"
primaryColor = "#4A90E2"    
backgroundColor = "#FFFFFF"  
secondaryBackgroundColor = "#F7F7F7"
textColor = "#333333"       
font = "DM Sans"

# Disable automatic theme switching
enableDarkTheme = false

[browser]
gatherUsageStats = false

[server]
port = 8501
enableCORS = false
fileWatcherType = "poll"
headless = true
enableThemeExtension = false
