[theme]
base = "light"
primaryColor = "#4A90E2"
backgroundColor = "#F4F4F4"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#333333"

[server]
port = 8501
enableCORS = false
fileWatcherType = "poll"
headless = true
