[theme]
primaryColor = "#4A90E2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"  # Actualizado para coincidir
textColor = "#333333"
font = "DM Sans"  # Agregar fuente principal
base = "light"

# Desactivar temas automáticos
enableDarkTheme = false

[browser]
gatherUsageStats = false

[server]
port = 8501
enableCORS = false
fileWatcherType = "poll"
headless = true
enableThemeExtension = false
