[theme]
base = "light"
primaryColor = "#4A90E2"        # Mantener - coincide con nuestro primary
backgroundColor = "#FFFFFF"      # Mantener - coincide con nuestro background
secondaryBackgroundColor = "#F7F7F7"  # Mantener - coincide con background_secondary
textColor = "#333333"           # Mantener - coincide con nuestro text
font = "sans serif"  

[browser]
gatherUsageStats = false

[server]
port = 8501
fileWatcherType = "poll"
headless = true

# Agregar para evitar cambios automáticos de tema
enableThemeWatcher = false
