[theme]
base = "light"
primaryColor = "#4A90E2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#333333"
# Solo valores "sans serif", "serif" o "monospace" son válidos.
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
port = 8501
fileWatcherType = "poll"
headless = true
