[theme]
base = "light"
primaryColor = "#4A90E2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#333333"
# Cambiamos DM Sans por sans serif (valor permitido)
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
port = 8501
fileWatcherType = "poll"
headless = true

# Si deseas desactivar la protección CSRF y CORS (no recomendado en producción),
# descomenta estas líneas:
# enableCORS = false
# enableXsrfProtection = false
