[theme]
base = "light"
primaryColor = "#4A90E2"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#333333"
font = "DM Sans"

[browser]
gatherUsageStats = false

[server]
port = 8501
fileWatcherType = "poll"
headless = true
# Si necesitas forzar CORS desactivado, añade:
# enableCORS = false
# enableXsrfProtection = false
# (Pero no es recomendable en producción)
